config/routes.rb
Blinder::Application.routes.draw do
  root 'collect#home'
  get  'review/:event_slug/proposal/:proposal_id' => 'review#detailed', as: :review
  get  'review/:event_slug' => 'review#list', as: :list
  post 'scrubs'  => 'control/proposals#scrub', as: :scrubs
  patch 'scrubs' => 'control/proposals#scrub', as: :scrub

  # omniauth provider callback for github auth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  controller :collect do
    get    ':event_slug', action: :home, as: :event
    get    ':event_slug/new', action: :new, as: :proposals
    get    'thanks/:slug', action: :thanks, as: :thanks
    get    'edit/:slug', action: :edit, as: :proposal
    post   ':event_slug/new', action: :create
    patch  'edit/:id', action: :update
  end

  resources :notes, only: [:create, :update]
  post 'rate' => 'ratings#rate', as: :rate

  namespace :control do
    resources :events, only: [:index, :edit, :update], param: :slug do
      resources :proposals
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :slug, uniqueness: true, length: { in: 3..10 }, presence: true

  has_many :proposals
  has_many :questions, through: :blinds
  has_many :responses, through: :proposals
  has_many :blinds, -> { order("position ASC") }

  scope :active,    -> { where('active = ? AND (expires_at is NULL OR ? <= expires_at)', true, Time.now) }
  scope :expired,   -> { where('? > expires_at', Time.now) }
  scope :inactive,  -> { where(active: false) }

  def expired?
    expires_at && expires_at.past?
  end

  def is_a_human?(key)
    key === human_key
  end

  # overload method to give the slug instead of the id if its present
  # this make our routes easier to deal with since built in methods like
  # `resources` and `link_to` will just work
  def to_param
    slug || id
  end
end

app/controllers/control/events_controller.rb
class Control::EventsController < ControlController
  def index
    @events = Event.order(:title).decorate
  end

  def edit
    @event = Event.where(slug: params[:slug]).first.decorate
  end

  def update
    event = Event.where(slug: params[:slug]).first
    clear_event_date :expires_at if params[:event][:expirable] == '0'
    event.update_attributes(event_update_params[:event])
    redirect_to action: :index
  end

  protected

  def event_update_params
    params.permit(event: [:title, :info, :inactive_info, :blind_level, :active, :expires_at])
  end

  def clear_event_date key
    params[:event].delete "#{key}(1i)"
    params[:event].delete "#{key}(2i)"
    params[:event].delete "#{key}(3i)"
    params[:event][key] = nil
  end
end

app/controllers/control/proposals_controller.rb
class Control::ProposalsController < ControlController
  def index
    @event  = Event.where(slug: params[:event_slug]).first
    @unsafe = @event.proposals.unsafe
    @safe   = @event.proposals.safe
  end

  def edit
    @proposal = Proposal.includes(responses: :scrub, event: :questions).find params[:id]
    @notes    = current_user.notes_for @proposal
    @proposal.event.blinds.each do |blind|
      blind.existing_responses_for @proposal
    end
  end

  def update
    @proposal = Proposal.find params[:id]
    @proposal.safe_for_review = params[:proposal][:safe_for_review]

    if @proposal.save
      flash[:notice] = "Proposal updated!"
      redirect_to action: :index
    else
      flash[:notice] = "Something went terribly wrong."
      redirect_to action: :edit
    end
  end

  def destroy
    Proposal.find(params[:id]).destroy
    redirect_to :back, notice: "Proposal destroyed!"
  end

  def scrub
    scrub = Scrub.find_or_create_by(response_id: scrub_ajax_params[:scrub][:response_id])
    scrub.update scrub_ajax_params[:scrub]
    render partial: 'review/response', locals: { response: scrub.response.decorate }
  end

  protected

  def scrub_ajax_params
    params.permit(scrub: [:response_id, :blind_level, :value])
  end

end

app/controllers/control_controller.rb
require_relative '../../lib/has_access'

class ControlController < ApplicationController
  include HasAccess
  before_filter :authenticate!
  before_filter :has_access?

  def proposal_list_for_event
    @event = Event.find(params[:id])
    unsafe = @event.proposals.unsafe
    safe = @event.proposals.safe
  end
end

app/helpers/control_helper.rb
module ControlHelper

end

app/views/control/events/_event.html.haml
= form_for event, url: control_event_path(event) do |f|
  .input
    = f.label :title
    = f.text_field :title
  .input
    = f.label :info
    = f.text_area :info
  .input
    = f.label :inactive_info
    = f.text_area :inactive_info
  .input
    %p.warning Changes to the blind level will take effect immidiately.
    = f.label :blind_level
    = f.text_field :blind_level
    %p.info
      %h3 Available Blinds
      %ul
        - event.blinds.by_level.each do |blind|
          %li!= "#{blind.level}: #{blind.title}"
    .input
      = f.label :active
      = f.check_box :active
    #expirable.input
      = f.label :expirable, 'Disable by Date'
      = f.check_box :expirable, :checked => !@event.expires_at.nil?
    #expires.input
      = f.label :expires_at
      = f.date_select :expires_at
  = f.submit

app/views/control/events/edit.html.haml
%h1 Edit Event
= render @event

app/views/control/events/index.html.haml
%h4 Events
%ol.events
  - @events.each do |event|
    %li
      = event.title
      = event.view_link
      = event.edit_link
      = event.proposals_link
      = event.state_list