config/routes.rb
Blinder::Application.routes.draw do
  root 'collect#home'
  get  'review/:event_slug/proposal/:proposal_id' => 'review#detailed', as: :review
  get  'review/:event_slug' => 'review#list', as: :list
  post 'scrubs'  => 'control/proposals#scrub', as: :scrubs
  patch 'scrubs' => 'control/proposals#scrub', as: :scrub

  # omniauth provider callback for github auth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  controller :collect do
    get    ':event_slug', action: :home, as: :event
    get    ':event_slug/new', action: :new, as: :proposals
    get    'thanks/:slug', action: :thanks, as: :thanks
    get    'edit/:slug', action: :edit, as: :proposal
    post   ':event_slug/new', action: :create
    patch  'edit/:id', action: :update
  end

  resources :notes, only: [:create, :update]
  post 'rate' => 'ratings#rate', as: :rate

  namespace :control do
    resources :events, only: [:index, :edit, :update], param: :slug do
      resources :proposals
    end
  end
end

app/views/shared/_errors.html.haml
.errors
  %h4 Uh oh! We found the following errors. Please review your entries and try submitting again.
  %ul
    - errors.each do |group, errors|
      != errors.map { |error| content_tag :li, error }.join

app/views/shared/_note_box.html.haml
%h4 Notes
= form_for notes, remote: true do |f|
  = f.hidden_field :id
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :proposal_id, value: proposal.id
  .note= f.text_area :content
  .submit
    .status
    = f.submit "Save"

app/views/shared/_rating.html.haml
%h4 Rate This Proposal
%span Not Recommended
- (1..5).each do |score|
  = form_tag '/rate' do
    = hidden_field_tag :slug, proposal.event.slug
    = hidden_field_tag :proposal_id, proposal.id
    = hidden_field_tag :score, score
    = submit_tag score, class: score_class(proposal, score)
%span Strongly Recommended

app/views/shared/_scrub_form.html.haml
= form_for scrub, remote: true do |f|
  = f.hidden_field :response_id, value: response_id
  = f.label :value, 'Scrubbed Response'
  = f.text_area :value
  = f.label :blind_level, 'Adjusted blind level'
  = f.text_field :blind_level, value: (f.object.blind_level || passed_blind_level), class: 'small'
  = f.submit "Scrub", class: 'small'
  .small.status

app/views/shared/_user_nav.haml
- if current_user
  .user_nav
    = "Hi #{ current_user.name }!"
    = link_to "Events", control_events_path if current_user.can? :control
    |
    = link_to "Review", list_path(params[:event_slug] || Event.last.slug) if current_user.can? :review
    |
    = link_to "Sign out", signout_path, id: "sign_out", method: :delete