config/routes.rb
Blinder::Application.routes.draw do
  root 'collect#home'
  get  'review/:event_slug/proposal/:proposal_id' => 'review#detailed', as: :review
  get  'review/:event_slug' => 'review#list', as: :list
  post 'scrubs'  => 'control/proposals#scrub', as: :scrubs
  patch 'scrubs' => 'control/proposals#scrub', as: :scrub

  # omniauth provider callback for github auth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  controller :collect do
    get    ':event_slug', action: :home, as: :event
    get    ':event_slug/new', action: :new, as: :proposals
    get    'thanks/:slug', action: :thanks, as: :thanks
    get    'edit/:slug', action: :edit, as: :proposal
    post   ':event_slug/new', action: :create
    patch  'edit/:id', action: :update
  end

  resources :notes, only: [:create, :update]
  post 'rate' => 'ratings#rate', as: :rate

  namespace :control do
    resources :events, only: [:index, :edit, :update], param: :slug do
      resources :proposals
    end
  end
end

app/controllers/collect_controller.rb
require 'postmark'

class CollectController < ApplicationController

  ROBOT_ERROR = "There was a problem validating your <span>human key</span>. Please try again.".html_safe

  def home
    if params[:event_slug]
      @event = Event.where(slug: params[:event_slug]).first.decorate
    else
      @event = Event.active.any? ? Event.active.first.decorate : Event.last.decorate
    end
  end

  def new
    @event = Event.includes(blinds: :questions).where(slug: params[:event_slug]).first.decorate
    redirect_to root_path unless @event.can_propose?

    @proposal = Proposal.new

    @event.blinds.each do |blind|
      blind.new_responses_for @proposal
    end
  end

  def create
    @proposal   = Proposal.new(proposal_create_params)
    @event      = Event.where(slug: params[:event_slug]).first
    @proposal.event = @event

    @is_a_human = @event.is_a_human?(params[:human_key])

    params.permit! # this is a terrible idea; someone please do this right.
    @proposal.responses.build(params[:responses])

    if @is_a_human && @proposal.save
      send_confirmation_email
      redirect_to thanks_path @proposal.slug
    else
      add_errors
      @event.blinds.each do |blind|
        blind.posted_responses_for @proposal
      end

      render action: :new
    end
  end

  def edit
    redirect_to root_path unless params[:slug]

    @proposal = Proposal.includes(responses: { question: :blind }).find_by_slug(params[:slug])
    @event = @proposal.event.decorate

    @event.blinds.each do |blind|
      blind.existing_responses_for @proposal
    end

    render action: @event.can_propose? ? :new : :home #lolhacky
  end

  def update
    @proposal   = Proposal.includes(:event, :responses).find(params[:id])
    @event      = @proposal.event
    @is_a_human = @event.is_a_human?(params[:human_key])

    @proposal.responses.each do |response|
      selected = response_update_params.find { |param| param[:id] == response.id.to_s }
      response.update(selected) if selected
    end

    if @is_a_human && @proposal.save
      send_confirmation_email
      redirect_to thanks_path @proposal.slug
    else
      add_errors
      @event.blinds.each do |blind|
        blind.posted_responses_for @proposal
      end

      render action: :new
    end
  end

  def thanks
    @proposal = Proposal.includes(event: { blinds: :questions }).find_by_slug params[:slug]
  end

  protected

  def add_errors
    @errors = @proposal.valid? ? { :"responses.base" => [] } : @proposal.errors.messages
    @errors[:"responses.base"].push(ROBOT_ERROR) unless @is_a_human
  end

  def proposal_create_params
    params.permit(:event_id, :slug, :responses)
  end

  def response_update_params
    params.permit(responses: [:id, :question_id, :value]).require(:responses)
  end

  def send_confirmation_email
    mailer = Postmark::ApiClient.new ENV['POSTMARK_API_KEY']
    mailer.deliver from:      ENV['CFP_FROM'],
                   to:        @proposal.get_email_address,
                   bcc:       ENV['CFP_BCC'],
                   subject:   "Thank you for submitting to #{ @proposal.event.title }!",
                   tag:       'cfp-thanks',
                   html_body: render_to_string(layout: false, template: "collect/thanks")
  end
end

app/helpers/collect_helper.rb
module CollectHelper
  def input_for(response)
    id      = "#{response.question.id}_value"
    name    = "responses[][value]"
    values  = response.question.values.blank? ? nil : response.question.values.split(',')

    case response.question.kind
      when "text"     then text_field_tag(name, response.value, id: id)
      when "tel"      then telephone_field_tag(name, response.value, id: id)
      when "email"    then email_field_tag(name, response.value, id: id)
      when "textarea" then text_area_tag(name, response.value, id: id)
      when "radio"    then radio_group(name, response.question.group, id, values, response.value)
      else ""
    end
  end

  def size_class_for(response)
    case response.question.kind
      when "textarea" then 'large'
      when "radio"    then 'small'
      else "other"
    end
  end

  def classes_for(question)
    question.required? ? "required" : ""
  end

  def form_title_for(proposal)
    if proposal.new_record?
      "Submit a New Proposal"
    else
      "Edit Your Proposal."
    end
  end

  protected

  def radio_group(name, group, id, values, selected)
    values.each_with_index.map { |value, index|
      indexed_id = "#{id}_#{index}"
      button = radio_button_tag "#{name}_#{group}", value, selected == value, id: indexed_id
      label_tag indexed_id, class: 'radio' do
        button + value
      end
    }.reduce &:+
  end
end

app/views/collect/home.html.haml
.event_info
  != @event.time_sensitive_infos
  %p.collect--getStarted
    = @event.submission_link

app/views/collect/new.html.haml
%h2= form_title_for @proposal 

- if @errors
  = render partial: 'shared/errors', locals: { errors: @errors }

%p.info
  %span.required *
  indicates a required field. You can use
  = link_to "Markdown", "http://whatismarkdown.com/", target: "_blank"
  to add formatting to your submission!

= form_for @proposal do |f|
  - @event.blinds.each do |blind|
    %section{ class: "blind" }
      %h3.title!= blind.title
      %p.info!= blind.info
      = render blind.responses
  %section{ class: "blind" }
    .question.other
      = label_tag "human_key", "To help us keep spam down, please enter '#{@event.human_key}' here.", class: 'required'
      = text_field_tag "human_key"

  = f.submit 'Submit Proposal', { class: "collect--submit" }

app/views/collect/thanks.html.haml
.thanks
  %h2 Thank you!
  %p
    We've received your proposal. You should receive an email confirmation in the next hour or so.
    If you have any questions or concerns, please contact our
    != "#{ mail_to ENV['CFP_FROM'], "CFP Team" }."
  %p
    Below is a copy of your submitted proposal. If you discover any errors or omissions, you can
    = link_to "edit your proposal.", proposal_url(@proposal.slug)
    You're welcome to edit this proposal until the CFP closes.

.review_proposal
  %h3= "Your proposal for #{ @proposal.event.title }"

  - @proposal.event.blinds.each do |blind|
    %section{ class: "blind" }
      %h4!= blind.title
      = render partial: 'review/response', collection: @proposal.responses_for(blind)