config/routes.rb
Blinder::Application.routes.draw do
  root 'collect#home'
  get  'review/:event_slug/proposal/:proposal_id' => 'review#detailed', as: :review
  get  'review/:event_slug' => 'review#list', as: :list
  post 'scrubs'  => 'control/proposals#scrub', as: :scrubs
  patch 'scrubs' => 'control/proposals#scrub', as: :scrub

  # omniauth provider callback for github auth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  controller :collect do
    get    ':event_slug', action: :home, as: :event
    get    ':event_slug/new', action: :new, as: :proposals
    get    'thanks/:slug', action: :thanks, as: :thanks
    get    'edit/:slug', action: :edit, as: :proposal
    post   ':event_slug/new', action: :create
    patch  'edit/:id', action: :update
  end

  resources :notes, only: [:create, :update]
  post 'rate' => 'ratings#rate', as: :rate

  namespace :control do
    resources :events, only: [:index, :edit, :update], param: :slug do
      resources :proposals
    end
  end
end

app/models/proposal.rb
require 'digest/sha1'

class Proposal < ActiveRecord::Base
  has_many   :responses, autosave: true
  has_many   :notes, dependent: :destroy
  has_many   :ratings, dependent: :destroy
  belongs_to :event

  after_create :generate_slug

  scope :listing,     -> { select(:id, :slug, :updated_at, :event_id) }
  scope :most_recent, -> { order('updated_at DESC') }
  scope :rated_by,    -> (user_id) { includes(:ratings).where(ratings: { user_id: user_id }) }
  scope :for_event,   -> (event_id) { listing.most_recent.where(event_id: event_id, safe_for_review: true) }
  scope :unsafe,      -> { listing.most_recent.where(safe_for_review: false) }
  scope :safe,        -> { listing.most_recent.where(safe_for_review: true) }

  accepts_nested_attributes_for :responses

  def user_score(user)
    user_ratings = ratings.where(user: user)
    user_ratings.any? ? user_ratings.first.score : 0
  end

  def responses_for(blind)
    question_ids = blind.questions.map &:id
    responses.where(question_id: question_ids).decorate
  end

  def response_for_question(question)
    responses.where(question_id: question.id).first.decorate
  end

  def get_email_address
    # I hate this method.
    # This exposes a fundamental weakness in my approach to this app. In the future,
    # this will need a refactor so that contact information is collected at the proposal level
    # rather than the blind level (or maybe through user accounts).
    q_id = event.questions.where(label: "Email Address").first.id
    responses.where(question_id: q_id).first.value
  end

  def get_title
    # I hate this method even more.
    # Everything that's terrible about get_email_address is true here too. This
    # method is worse because now I'm emulating a pattern that I know is busted.
    q_id = event.questions.where(label: "Talk Title").first.id
    responses.where(question_id: q_id).first.value
  end

  def notes_for_user(user)
    notes.where(user: user).first
  end

  protected

  def generate_slug
    seed = self.responses.any? ? self.responses.sample.value : random_seed
    self.slug = Digest::SHA1.hexdigest(Time.now.to_s + seed)
    save!
  end

  def random_seed
    %w(taco _elephant werewolf submarine fern5 trampoline satellite fight! window).sample
  end
end

app/controllers/control/events_controller.rb
class Control::EventsController < ControlController
  def index
    @events = Event.order(:title).decorate
  end

  def edit
    @event = Event.where(slug: params[:slug]).first.decorate
  end

  def update
    event = Event.where(slug: params[:slug]).first
    clear_event_date :expires_at if params[:event][:expirable] == '0'
    event.update_attributes(event_update_params[:event])
    redirect_to action: :index
  end

  protected

  def event_update_params
    params.permit(event: [:title, :info, :inactive_info, :blind_level, :active, :expires_at])
  end

  def clear_event_date key
    params[:event].delete "#{key}(1i)"
    params[:event].delete "#{key}(2i)"
    params[:event].delete "#{key}(3i)"
    params[:event][key] = nil
  end
end

app/controllers/control/proposals_controller.rb
class Control::ProposalsController < ControlController
  def index
    @event  = Event.where(slug: params[:event_slug]).first
    @unsafe = @event.proposals.unsafe
    @safe   = @event.proposals.safe
  end

  def edit
    @proposal = Proposal.includes(responses: :scrub, event: :questions).find params[:id]
    @notes    = current_user.notes_for @proposal
    @proposal.event.blinds.each do |blind|
      blind.existing_responses_for @proposal
    end
  end

  def update
    @proposal = Proposal.find params[:id]
    @proposal.safe_for_review = params[:proposal][:safe_for_review]

    if @proposal.save
      flash[:notice] = "Proposal updated!"
      redirect_to action: :index
    else
      flash[:notice] = "Something went terribly wrong."
      redirect_to action: :edit
    end
  end

  def destroy
    Proposal.find(params[:id]).destroy
    redirect_to :back, notice: "Proposal destroyed!"
  end

  def scrub
    scrub = Scrub.find_or_create_by(response_id: scrub_ajax_params[:scrub][:response_id])
    scrub.update scrub_ajax_params[:scrub]
    render partial: 'review/response', locals: { response: scrub.response.decorate }
  end

  protected

  def scrub_ajax_params
    params.permit(scrub: [:response_id, :blind_level, :value])
  end

end

app/controllers/control_controller.rb
require_relative '../../lib/has_access'

class ControlController < ApplicationController
  include HasAccess
  before_filter :authenticate!
  before_filter :has_access?

  def proposal_list_for_event
    @event = Event.find(params[:id])
    unsafe = @event.proposals.unsafe
    safe = @event.proposals.safe
  end
end

app/helpers/control_helper.rb
module ControlHelper

end

app/views/control/proposals/edit.html.haml
%h2 Proposal Review
- @proposal.event.blinds.each do |blind|
  %section.blind.review
    %h3!= blind.title
    %p.info!= blind.info + " (blind level: #{blind.level})"
    = render partial: 'review/response', collection: blind.decorated_responses

= form_for @proposal, url: control_event_proposal_path(@proposal.event, @proposal) do |f|
  %section.question
    = f.label :safe_for_review, "Is this proposal ready for review by the selection committee?"
    %label.radio!= "#{ f.radio_button :safe_for_review, '0', checked: true } No"
    %label.radio!= "#{ f.radio_button :safe_for_review, '1' } Yes"
  %section
    = f.submit

#notes= render partial: 'shared/note_box', locals: { notes: @notes, proposal: @proposal }

app/views/control/proposals/index.html.haml
%h4= "Proposals for #{ @event.title }"
.proposal_list
  %h5 Proposals needing review
  %ol.proposals
    - @unsafe.each do |proposal|
      %li
        = link_to proposal.slug[0,6], edit_control_event_proposal_path(@event, proposal), class: 'slug'
        %span.destroy= link_to '(destroy)', control_event_proposal_path(@event, proposal), method: :delete, :'data-confirm' => "Destroy for realsies?"
        %span.notes=  notes_for proposal
        %span.updated= "updated: #{ last_updated proposal }"

.proposal_list
  %h5 Safe for Review Proposals
  %ol.proposals
    - @safe.each do |proposal|
      %li
        = link_to proposal.slug[0,6], edit_control_event_proposal_path(@event, proposal), class: 'slug'
        %span.notes=  notes_for proposal
        %span.updated= "updated: #{ last_updated proposal }"